import type { KeyType } from "../components/Key.tsx";

export type KeyboardLayout = {
  name: string;
  left: KeyType[];
  right: KeyType[];
};

export const defaultLayout: KeyboardLayout = {
  name: "default",
  left: [
    {
      action: "insert",
      payload: "1",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "2",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "3",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "4",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "5",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "q",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "w",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "e",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "r",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "t",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "a",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "s",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "d",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "f",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "g",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "z",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "x",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "c",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "v",
      width: 1,
      height: 1,
    },
    {
      label: "←",
      action: "cursor",
      payload: -1,
      width: 2,
      height: 1,
    },
    {
      label: "Space",
      action: "insert",
      payload: " ",
      width: 3,
      height: 1,
    },

    {
      action: "blank",
      payload: undefined,
      width: 1,
      height: 1,
    },

    {
      label: "Aa",
      action: "switchLayout",
      payload: "defaultShift",
      width: 3,
      height: 1,
    },
  ],
  right: [
    {
      action: "insert",
      payload: "6",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "7",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "8",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "9",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "0",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "y",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "u",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "i",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "o",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "p",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "h",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "j",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "k",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "l",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "b",
      width: 1,
      height: 1,
    },
    {
      action: "blank",
      payload: undefined,
      width: 1,
      height: 1,
    },
    {
      label: "፧",
      action: "switchInput",
      payload: "commandMode",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "n",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "m",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: ".",
      width: 1,
      height: 1,
    },
    {
      label: "backspace",
      action: "remove",
      payload: 1,
      width: 3,
      height: 1,
    },
    {
      label: "→",
      action: "cursor",
      payload: 1,
      width: 2,
      height: 1,
    },
    {
      action: "blank",
      payload: undefined,
      width: 1,
      height: 1,
    },
    {
      action: "blank",
      payload: undefined,
      width: 1,
      height: 1,
    },
    {
      label: "Enter",
      action: "enter",
      payload: 1,
      width: 3,
      height: 1,
    },
  ],
};

export const defaultLayoutShift: KeyboardLayout = {
  name: "defaultShift",
  left: [
    {
      action: "insert",
      payload: "!",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "@",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "#",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "$",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "%",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "Q",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "W",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "E",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "R",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "T",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "A",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "S",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "D",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "F",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "G",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "Z",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "X",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "C",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "V",
      width: 1,
      height: 1,
    },
    {
      label: "←",
      action: "cursor",
      payload: -1,
      width: 2,
      height: 1,
    },
    {
      label: "Space",
      action: "insert",
      payload: " ",
      width: 3,
      height: 1,
    },
    {
      action: "blank",
      payload: undefined,
      width: 1,
      height: 1,
    },
    {
      label: "aA",
      action: "switchLayout",
      payload: "default",
      width: 3,
      height: 1,
    },
  ],
  right: [
    {
      action: "insert",
      payload: "^",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "&",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "*",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "(",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: ")",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "Y",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "U",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "I",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "O",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "P",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "H",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "J",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "K",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "L",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "B",
      width: 1,
      height: 1,
    },
    {
      action: "blank",
      payload: undefined,
      width: 1,
      height: 1,
    },
    {
      label: "፧",
      action: "switchInput",
      payload: "commandMode",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "N",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: "M",
      width: 1,
      height: 1,
    },
    {
      action: "insert",
      payload: ".",
      width: 1,
      height: 1,
    },
    {
      label: "backspace",
      action: "remove",
      payload: 1,
      width: 3,
      height: 1,
    },
    {
      label: "→",
      action: "cursor",
      payload: 1,
      width: 2,
      height: 1,
    },
    {
      action: "blank",
      payload: undefined,
      width: 1,
      height: 1,
    },
    {
      action: "blank",
      payload: undefined,
      width: 1,
      height: 1,
    },
    {
      label: "Enter",
      action: "enter",
      payload: 1,
      width: 3,
      height: 1,
    },
  ],
};

export const FallbackLayouts = {
  [defaultLayout.name]: defaultLayout,
  [defaultLayoutShift.name]: defaultLayoutShift,
};
